# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'yaxzo_maps.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(790, 493)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.map_label = QtWidgets.QLabel(self.centralwidget)
        self.map_label.setGeometry(QtCore.QRect(0, 0, 600, 450))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(False)
        self.map_label.setFont(font)
        self.map_label.setTextFormat(QtCore.Qt.AutoText)
        self.map_label.setAlignment(QtCore.Qt.AlignCenter)
        self.map_label.setObjectName("map_label")
        self.search_query = QtWidgets.QLineEdit(self.centralwidget)
        self.search_query.setGeometry(QtCore.QRect(630, 110, 151, 31))
        self.search_query.setObjectName("search_query")
        self.info_label = QtWidgets.QLabel(self.centralwidget)
        self.info_label.setGeometry(QtCore.QRect(630, 60, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setBold(False)
        self.info_label.setFont(font)
        self.info_label.setObjectName("info_label")
        self.search_button = QtWidgets.QPushButton(self.centralwidget)
        self.search_button.setGeometry(QtCore.QRect(630, 150, 101, 31))
        self.search_button.setObjectName("search_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 790, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Yaxzo.Maps", "Yaxzo.Maps"))
        self.map_label.setText(_translate("MainWindow", "Здесь будет ваша карта"))
        self.info_label.setText(_translate("MainWindow", "Что отобразить на карте?"))
        self.search_button.setText(_translate("MainWindow", "Искать"))
